### ISSUE TITLE
Use interactive Clojure wrapper

### ISSUE THREAD

**Issue by Deraen** [liquidz/vim-iced#175] opened 2020-01-15 15:48 UTC
Currently `iced` script calls `clojure` command for `deps.edn` projects.

This doesn't work well when trying to use the REPL directly, as `clojure` program doesn't support readline, i.e. command history, up/down arrows...

> clj is a wrapper for interactive repl use.

https://clojure.org/reference/deps_and_cli

I didn't check if the vim-iced also uses the command internally, for jackin or something. `clj` should be used always when running command from interactive shell, `clojure` for non-interactive shells like CI environments and possibly if using inside another process.

If you need to check shell is interactive, checking if `$-` contains `i` could work.

**Comment by liquidz** [comment] 2020-01-16 00:20
@Deraen Thanks for your suggestion!

Currently, running just `iced repl` won't start REPL for Clojure CLI project.
https://github.com/liquidz/vim-iced/blob/0.14.0/bin/iced#L310-L311

Are you sure that you are using `-r` or `--repl` option?
https://github.com/nrepl/nrepl/blob/master/src/clojure/nrepl/cmdline.clj#L115

If so, it is reasonable to use `clj` command instead of `clojure` command as you said.

Btw, is it more usable to use `--repl` option in `iced` command by default?

**Comment by micheam** [comment] 2020-01-16 02:36
> Btw, is it more usable to use --repl option in iced command by default?

I agree with this ✋!!!


Currently, I set alias below in my .bashrc 😔
```bash
alias iced-repl='iced repl -A:dev:test --repl'
```

**Comment by Deraen** [comment] 2020-01-16 08:04
Huh, what does the `--repl` option do? I've never used it and it isn't documented.

**Comment by liquidz** [comment] 2020-01-17 07:13
@Deraen Sorry, it seems `--interactive` is correct as a nREPL option for launching REPL.
I changed to use `clj` command and set `--interactive` option by default for `deps.edn` project.

Could you try `dev` branch?

**Comment by Deraen** [comment] 2020-01-17 07:47
Yep, REPL works now.

I guess I should create another issue, but: another issue with the wrapper is that the script adds local-root dependency to iced-repl. This breaks reloaded.repl/integrant-repl/clojure.tools.namespace refresh workflow, as it now tries to reload all files in source-paths, and this fails as `iced_jackin` file requires mokuhan.

**Comment by liquidz** [comment] 2020-01-17 09:18
@Deraen Thanks for your confirmation!
I could reproduce the problem with `clojure.tools.namespace.repl/refresh`.

I separated paths for `iced-repl` and `iced-jackin` and the problem was fixed in my environment.
Could you try the latest `dev` branch again?
NOTE: if you have a `.cpcache` directory on your project, please remove it at first.

**Comment by liquidz** [comment] 2020-01-21 13:20
@Deraen Thanks!
I'll cut a new release this weekend!

**Comment by liquidz** [comment] 2020-01-21 13:22
@micheam Could you try `dev` branch too?
`iced repl` should start REPL without your alias setting.

**Comment by micheam** [comment] 2020-01-21 13:54
@liquidz 
It works 🤩Thanks a lot !!

**Comment by liquidz** [comment] 2020-01-21 13:59
@micheam Thanks for your confirmation!

**Comment by liquidz** [comment] 2020-01-23 09:46
Closed by #181

**Closed by liquidz** 2020-01-23 09:46 UTC
Labels: enhancement, next release
