### ISSUE TITLE
:IcedFormatAll messes with marks and cursor

### ISSUE THREAD

**Issue by nbardiuk** [liquidz/vim-iced#178] opened 2020-01-20 08:36 UTC
Some annoyances with the `:IcedFormatAll` command related to marks and cursor:

 * `:IcedFormatAll` removes lowercase marks `[a-z]`

 * `:IcedFormatAll` changes marks related to selection `'< '>` such that the `gv` selects namespace declaration on top of the buffer instead of what user has selected previously.

 * The `undo` after `:IcedFormatAll` jumps the cursor to the top of the buffer.

**Comment by liquidz** [comment] 2020-01-20 11:57
@nbardiuk Thanks for your reporting!
I could reproduce those problems.
I'll fix them.

**Comment by liquidz** [comment] 2020-01-21 09:08
@nbardiuk I fixed reported problems in `dev` branch.
Could you try `dev` branch?

Other operations may have same problems.
I'll fix them when I find.

**Comment by nbardiuk** [comment] 2020-01-21 21:20
Tested on `dev` all issues are resolved :fireworks: :tada: 

I've noticed one strange behavior:
 1. put cursor on line of code
 2. `:IcedFormatAll`
 3. `undo`
 4. goto 2.

each cycle of `:IcedFormatAll`+`undo` adds one space at the cursor position

**Comment by liquidz** [comment] 2020-01-21 23:29
@nbardiuk Thanks!

> I've noticed one strange behavior:

I couldn't reproduce the problem.
But the following code that set a undo point may be the cause.
https://github.com/liquidz/vim-iced/commit/df12dec31af0181599dc27a034d360bed08feeb0#diff-a9dfee86c7d0035e9466b1a77f1cb841R49

To set undo point, `IcedFormatAll` insert one space and delete it internally.
This process uses `:normal!` command, so it should not be affected any custom mappings...
https://vim-jp.org/vimdoc-en/various.html#:normal

I'll verify it a bit more.

**Comment by nbardiuk** [comment] 2020-01-22 07:30
Don't worry about this, the problem is in my config : 

`autocmd TextChanged,InsertLeave * if &modified | :w | endif`  

this autosave command writes file on `esc` when plugin executes `normal! i \<esc>x`

I knew this autosave should cause me troubles, but I was very curious where it will brake first.

**Comment by liquidz** [comment] 2020-01-22 11:56
OK😊
Thank you for notifying me!

**Comment by liquidz** [comment] 2020-01-23 09:50
Closed by #181

**Closed by liquidz** 2020-01-23 09:50 UTC
Labels: bug, next release
