### ISSUE TITLE
Redrawing glitches when an exception is thrown

### ISSUE THREAD

**Issue by daveyarwood** [liquidz/vim-iced#65] opened 2018-12-13 20:28 UTC
# Details of my setup

* Ubuntu 16.04
* Neovim v0.3.2-dev
* tmux v2.9

# Steps to reproduce

1. Start `iced repl` in another window.
2. Connect to it via `:IcedConnect`.
3. Evaluate a form that throws an exception, like `(throw (ex-info "oops" {}))`

# Expected behavior

The exception message is displayed.

# Actual behavior

The exception message is displayed, but the lines in the buffer also redraw strangely:

![2018-12-13-152217_724x435_scrot](https://user-images.githubusercontent.com/4909079/49965357-f457d780-feea-11e8-9825-22e01f41d0a3.png)

I'm able to get things back to normal by scrolling up and down the file; as my cursor enters each line, it redraws correctly.

**Comment by liquidz** [comment] 2018-12-13 22:08
@daveyarwood Thanks for your reporting!
I tested the behaivior with nvim 0.3.2-dev, and it is reproduced.
But no problem with nvim 0.3.1 (current stable).

Perhaps it might be a bug in 0.3.2-dev, so could you test it with 0.3.1?

**Comment by liquidz** [comment] 2018-12-13 22:42
I will test with 0.3.2-dev more.

**Comment by liquidz** [comment] 2018-12-14 00:42
The problem occurs at here:
https://github.com/liquidz/vim-iced/blob/0.8.6/autoload/iced/nrepl.vim#L150

And this calls `nvim_buf_set_lines` finally.
https://github.com/liquidz/vim-iced/blob/0.8.6/autoload/iced/compat.vim#L18

**Comment by liquidz** [comment] 2018-12-17 10:43
@daveyarwood Thanks!
Probably nvim's this bug is the cause.
https://github.com/neovim/neovim/issues/7756

I can confirm that restoring cursor position after `nvim_buf_set_lines` prevent the problem. (this is workaround)

I will push the code after some testing!

**Comment by liquidz** [comment] 2018-12-18 07:48
@daveyarwood I pushed codes to `dev` branch.
Could you try `dev` branch with nvim 0.3.2-dev?

**Comment by daveyarwood** [comment] 2018-12-19 15:16
@liquidz I tried the dev branch of vim-iced with nvim 0.3.2-dev. The issue is fixed! :tada:

**Comment by liquidz** [comment] 2018-12-20 09:19
Fixed by #68

**Closed by liquidz** 2018-12-20 09:19 UTC

**Comment by daveyarwood** [comment] 2018-12-20 12:15
Awesome, thanks!
