### ISSUE TITLE
Not Found error when testing namespace

### ISSUE THREAD

**Issue by devth** [liquidz/vim-iced#77] opened 2019-01-04 17:08 UTC
I'm trying out vim-iced on my project, using https://github.com/yetibot/yetibot.core/blob/master/test/yetibot/core/test/commands/render.clj as an example test.

I'm using the default key mappings.

1. I try `<Leader>tn` and it givevs me `Not found.`
1. I try `<Leader>tt` on line 10 (or any line) and it gives me `No test vars.`
1. I try `<Leader>rcn` to clean and unexpectedly it removes my `[yetibot.core.commands.render :refer :all]` require, which is the ns under test. Not sure why?

I can `<Leader>eb` or `<Leader>eB` and those both work.

**Comment by liquidz** [comment] 2019-01-05 00:49
@devth Thank you for reporting!
vim-iced expects test files that namespace named "*-test" currently.
So I'll fix to work tests without "-test" namespaces.

**Comment by liquidz** [comment] 2019-01-07 08:09
@devth I fixed behaviors for `<Leader>tn` and `<Leader>tt` in `dev` branch.
Could you test it?

> I try <Leader>rcn to clean and unexpectedly it removes my [yetibot.core.commands.render :refer :all] require, which is the ns under test. Not sure why?

This is the problem of [refactor-nrepl](https://github.com/clojure-emacs/refactor-nrepl).
vim-iced is just using refactor-nrepl's `clean-ns` operation. 
Probably it is the cause that `yetibot.core.commands.render/render-cmd` is not called from `yetibot.core.test.commands.render` directly.

I can confirm that adding `(comment (render-cmd {}))` to the bottom of test codes avoid to remove it,
but ... I have no idea for the fundamental solution.

**Comment by devth** [comment] 2019-01-07 13:18
I verified it works! Thanks for the quick fix!

I noticed when I first run `<leader>tt` there is a slight delay that locks up my neovim for a few seconds. After the initial run the delay is gone.

**Comment by liquidz** [comment] 2019-01-08 00:00
> I noticed when I first run <leader>tt there is a slight delay that locks up my neovim for a few seconds. After the initial run the delay is gone.

@devth Thank you for the verification!
`<Leader>tt` evaluates `ns` form internally, so it seems to take times for requiring the current namespace.
Is the delay gone by running `<Leader>eb` (`:IcedRequire`) before `<Leader>tt`?

**Comment by devth** [comment] 2019-01-08 00:02
Yes. But when I run `<Leader>eb` the delay is quite long, about 10 seconds. During this time NeoVim is completely locked up. Since nvim is async I would expect this to happen in the background instead of locking up.

**Comment by liquidz** [comment] 2019-01-08 00:30
@devth Hmm.. `<Leader>eb` works asynchronously.
It may be another problem.
Could you open another issue?

**Comment by devth** [comment] 2019-01-08 00:43
Certainly

**Comment by liquidz** [comment] 2019-01-15 08:49
closed by #84

**Closed by liquidz** 2019-01-15 08:49 UTC
Labels: bug
