### ISSUE TITLE
`iced_test_ns` consistently "Interrupted"

### ISSUE THREAD

**Issue by mwistrand** [liquidz/vim-iced#183] opened 2020-02-22 15:04 UTC
When executing `iced_test_ns` in neovim 0.4.3, in either a leiningen or deps.edn project, the tests appear to hang before the message "Interrupted" is displayed. Running individual tests with `iced_test_under_cursor` works perfectly, however.

P.S. Thanks for your work on this project and for making it publicly available!

**Comment by liquidz** [comment] 2020-02-22 23:05
@mwistrand Thanks for your reporting!

I couldn't reproduce the problem in my project codes, but I could reproduce the problem with following steps.

* lein new foo && cd foo
* nvim test/foo/core_test.clj
* Execute `:IcedJackIn` command
* Execute `:IcedTestNs` command

I'll fix it!

**Comment by liquidz** [comment] 2020-02-22 23:27
@mwistrand I verified the problem has been fixed in my environment.
Could you try `dev` branch?

**Comment by mwistrand** [comment] 2020-02-23 14:08
@liquidz Everything seems to work fine on `dev`. Thanks for taking the time to fix this and for responding so quickly!

**Comment by liquidz** [comment] 2020-02-23 22:09
@mwistrand Thanks for your verification!
Closed by #184

**Closed by liquidz** 2020-02-23 22:09 UTC
Labels: bug, neovim
