### ISSUE TITLE
Couldn't find definition / Not found

### ISSUE THREAD

**Issue by devth** [liquidz/vim-iced#109] opened 2019-03-23 16:44 UTC
Trying iced out on https://github.com/yetibot/yetibot/blob/edfbdc52c6095b6a6affb8f15fe6c63f68042e47/src/yetibot/commands/weather.clj#L59

If i use `<C-d>` on any symbol in this ns it just says `Couldn't find definition`. If I run `:IcedSourceShow` when my cursor is on a symbol like `c-to-f` it says `Not found.`.

**Comment by liquidz** [comment] 2019-03-24 02:19
@devth

> If i use <C-d> on any symbol in this ns it just says Couldn't find definition. 

`Couldn't find definition` may not be vim-iced's error message.
https://github.com/liquidz/vim-iced/blob/master/message/iced/en.txt
What is `<C-d>` mapped to?

> If I run :IcedSourceShow when my cursor is on a symbol like c-to-f it says Not found..

`clojure.repl/source` could not read the source from evaluated vars.
This is a clojure specification.

* https://clojure.github.io/clojure/clojure.repl-api.html#clojure.repl/source
* https://stackoverflow.com/questions/41247416/repl-source-function-does-not-work-in-clojure

**Comment by devth** [comment] 2019-03-25 03:21
Oops I meant `]d`. It isn't mapped to anything. Looks like it's a built in vim thing. When I used fireplace I think it overrode `]d` to show source. So nevermind about the `Couldn't find definition` error.

Not sure why I see`Not found` when I try `:IcedSourceShow` since I am trying to get the source of a function in a namespace that is stored on disk 🤔 .

**Comment by liquidz** [comment] 2019-06-24 15:06
@devth It may be better to find source  by oneself instead of `clojure.repl/source` like this tweet.
https://twitter.com/uochan/status/1143170332078985216

**Comment by liquidz** [comment] 2019-06-25 13:55
@devth I tried to fix `IcedSourceShow` command in `dev` branch.

**Comment by devth** [comment] 2019-07-28 17:28
@liquidz I tried `dev` branch but looks like it's not working. I also can't seem to lookup docstrings or navigate to namespaces either:

`S-K`:

![image](https://user-images.githubusercontent.com/86107/62010626-7a4b2a80-b12a-11e9-9555-20073d5c9813.png)


`gf`:

![image](https://user-images.githubusercontent.com/86107/62010631-8afba080-b12a-11e9-8959-87d2fc8ac158.png)

`IcedSourceShow`:

![image](https://user-images.githubusercontent.com/86107/62010636-977ff900-b12a-11e9-8449-a10e315aa111.png)

**Comment by liquidz** [comment] 2019-07-29 01:46
@devth Thanks for your reporting!
I tested [master branch's yetibot/core/parser.clj](https://github.com/yetibot/yetibot.core/blob/master/src/yetibot/core/parser.clj) with `vim 8.1.1662` and `nvim 0.3.8(stable)`, but I could not reproduce the problem.

I tested with following steps.
* Run `iced repl`  to launch REPL
* Open `src/yetibot/core/parser.clj`
* Execute `:IcedConnect`
* Test `S-k`, `C-]`, and `:IcedSourceShow`

What version of vim/nvim do you use?

**Comment by devth** [comment] 2019-07-29 18:48
I'm on `NVIM v0.4.0-1281-g969618e`. Sorry for the false alarm - it looks like I had started a regular `lein repl` instead of `iced repl`.

I re-tested on latest `dev` branch. Everything's working, including `:IcedSourceShow`!

**Comment by liquidz** [comment] 2019-07-29 23:59
@devth Great!

> it looks like I had started a regular lein repl instead of iced repl.

Oh, it seems necessary to check if nREPL middleware is enabled.
I'll implement it!

**Comment by liquidz** [comment] 2019-08-03 20:51
Fixed by #125

**Closed by liquidz** 2019-08-03 20:51 UTC
