### ISSUE TITLE
Error using IcedInstantConnect IcedJackIn

### ISSUE THREAD

**Issue by tami5** [liquidz/vim-iced#271] opened 2020-09-23 15:50 UTC
I have an issue, using `IcedInstantConnect` and `IcedJackIn`.

![](https://i.imgur.com/3ujoINp.png)

Creating a external repl and hiting IcedConnect works well. Additionally, Using IcedInstantConnect babashka, Works okay, but . _DOC POPUP doesn't auto close when moving the cursor, or auto close by it self_

So its two issues, wrapped in one
1. `IcedInstantConnect` and `IcedJackIn` doesn't work with the above error message.
2. `IcedInstantConnect babashka` with `let g:iced#repl#babashka_repl_type = 'nrepl'` works well but doc popup doesn't close unless I do `:IcedDocumentPopupOpen<CR>`  on another form.

Thanks
BYT: I'm using dev branch, if its worth knowing

**Comment by liquidz** [comment] 2020-09-23 21:17
@tami5 Thanks for your reporting!

> IcedInstantConnect and IcedJackIn doesn't work with the above error message.

I could reproduce the problem. I'll fix.

> IcedInstantConnect babashka with let g:iced#repl#babashka_repl_type = 'nrepl' works well but doc popup doesn't close unless I do :IcedDocumentPopupOpen<CR> on another form.

In my environment, I could not reproduce on vim 8.2.1665 / nvim 0.4.4.
Moving the cursor horizontally doesn't close the popup by specification, but moving vertically does.

What is your vim/nvim version?
Could you try minimal configuration?
https://liquidz.github.io/vim-iced/#minimal_configuration

**Comment by tami5** [comment] 2020-09-23 21:35
Sure thing, My neovim version is 0.5. I'll try to reproduce with minimal configuration tonight popup not closing my it self tonight. Also is there I timer I can set?

Thanks

**Comment by liquidz** [comment] 2020-09-24 04:19
Currently auto closing feature is disabled for document popup.
https://github.com/liquidz/vim-iced/blob/2.3.1/autoload/iced/nrepl/document.vim#L150

Ah, I remember that the neovim popup relies on `CursorMoved` autocmd.
https://github.com/liquidz/vim-iced/blob/2.3.1/ftplugin/clojure.vim#L322-L329
Are you sure that the file you are opening have one of the following extentions?
> *.clj,*.cljs,*.cljc

**Comment by liquidz** [comment] 2020-09-24 21:36
@tami5 Ah, sorry, vim-iced was resetting the jackin job when connected.
https://github.com/liquidz/vim-iced/blob/2.3.1/autoload/iced/nrepl/connect.vim#L144

I fixed `IcedInstantConnect` and `IcedJackIn`.
Could you try `dev` branch?

**Comment by tami5** [comment] 2020-09-25 20:47
> Ah, I remember that the neovim popup relies on CursorMoved autocmd.
https://github.com/liquidz/vim-iced/blob/2.3.1/ftplugin/clojure.vim#L322-L329
Are you sure that the file you are opening have one of the following extentions?

Moving vertically closes it, I'm sure after testing. However, horizontally does.

> I fixed IcedInstantConnect and IcedJackIn. Could you try dev branch?

Unfortunately it didn't work, I get a message saying it found a lein project but nothing works.

**Comment by liquidz** [comment] 2020-09-25 21:07
> Moving vertically closes it, I'm sure after testing. However, horizontally does.

As I said, moving the cursor horizontally doesn't close the popup by specification.
It's because popup will closes even when you enter text.

> Unfortunately it didn't work, I get a message saying it found a lein project but nothing works.

Umm, weird.
In my environment, I confirm to work `IcedInstantConnect` and `IcedJackIn` with vim 8.2.1522 and nvim 0.5.0-709.
Just to clarify: Are you sure you are using the latest `dev` branch?

**Comment by tami5** [comment] 2020-09-25 21:30
>  Just to clarify: Are you sure you are using the latest dev branch?
Yes, commit a18f80 . 

Also is it normal for bakasha to not have jump to def and docs. Thanks

**Comment by liquidz** [comment] 2020-09-25 21:51
> Also is it normal for bakasha to not have jump to def and docs. Thanks

Currently yes.
The nREPL connection basically relies on cider-nrepl, so there are still many things we can't do with babashka.nrepl.

But now that we have clj-kondo static analysis available, I have a plan to implement def jumps based on it.

**Comment by liquidz** [comment] 2020-09-30 21:36
@tami5 I added an `g:iced#nrepl#connect#auto_connect_timeout` option to try it out.
The default value is `5000` (5 seconds).

Try changing the settings as needed.

**Comment by tami5** [comment] 2020-09-30 21:43
What does this option do exactly? 
Thanks

**Comment by liquidz** [comment] 2020-09-30 21:59
vim-iced confirms that "nREPL server started" is output and then starts trying to connect to the nREPL.
This option is the number of seconds to time out when trying to connect.

**Comment by tami5** [comment] 2020-09-30 23:33
I'll try it out hopefully tomorrow and report back, thanks so much!!

**Comment by liquidz** [comment] 2020-10-04 21:18
Renamed `g:iced#nrepl#connect#auto_connect_timeout` to `g:iced#nrepl#connect#auto_connect_timeout_ms`, and added help.
https://github.com/liquidz/vim-iced/blob/c6a58ebf8b2a54a3640f0b5a1fbfe6dabb4b31a6/doc/vim-iced.txt#L1578-L1583

**Comment by liquidz** [comment] 2020-10-06 20:40
I've cut a new release it in its current state for now. #272 
Feel free to reopen this issue with any trouble.

**Closed by liquidz** 2020-10-06 20:40 UTC
Labels: bug

**Comment by tami5** [comment] 2020-10-07 03:38
Hay, @liquidz  I'm terribly sorry for not being able to test it out till now. Thanks so much for looking into it and I'm sure its now fixed for the next time I open a clojure project. Thanks again

**Comment by liquidz** [comment] 2020-10-07 03:40
@tami5 Thanks for your confirmation!
