### ISSUE TITLE
Shadow-cljs watch hangs when connected with vim-iced

### ISSUE THREAD

**Issue by knubie** [liquidz/vim-iced#128] opened 2019-06-16 15:53 UTC
liquidzさん　こんにちは
残念ながらもう一つshadow-cljsについて問題は見つかりました。

Hi liquidz!
I'm sorry to say that I've found another bug related to shadow-cljs. The steps to reproduce are below:
1. Clone [minimal-shadow-cljs-browser](https://github.com/minimal-xyz/minimal-shadow-cljs-browser)
1. Install/watch
```sh
yarn
(mkdir -p target && cp assets/index.html target/)
yarn shadow-cljs watch app
```
1. Open browser to connect; localhost:8080
1. Open `src/main.cljs` in vim
1. Run `:IcedStartCljsRepl shadow-cljs app`
1. Modify the file and save. E.g. add `(def e 3)`
1. Evaluate a form. (Try evaluating `(def e 3)`)
1. Open `src/lib.cljs`
1. Modify the file and save. E.g. change `(def c 1)` to `(def c 10)`
1. Go back to `src/main.cljs`
1. Modify the file and save. E.g. add `(def f 4)`
1. Repeat 6. - 11. until the compiler hangs.
1. *Notice:* the the shadow-cljs watch process hangs on `Compiling ...` or fails to compile at all.

Unfortunately I am not able to reproduce this 100% of the time, but modifying/saving/eval-ing back and forth between both files will eventually result in the compiler hanging.

Let me know if you need any more info!

ありがとうございます

**Comment by liquidz** [comment] 2019-06-16 23:02
@knubie Thanks for your reporting!
I confirmed the behavior.

**Comment by liquidz** [comment] 2019-06-17 18:00
The prosess to set cljs session may be the cause of this behavior.
https://github.com/liquidz/vim-iced/blob/0.10.4/autoload/iced/nrepl/cljs.vim#L4

In normal clj session, shadow-cljs watch does not hang.

I'll test more.

**Comment by liquidz** [comment] 2019-06-18 04:28
@knubie I fixed the bug in `bugfix/shadow-cljs` branch.
https://github.com/liquidz/vim-iced/tree/bugfix/shadow-cljs

Could you try this branch?

**Comment by knubie** [comment] 2019-06-19 01:32
@liquidz I tested that branch on the minimal-shadow-cljs-browser repo, as well as on my own large cljs project, and everything seems good now! 👍

**Comment by liquidz** [comment] 2019-06-19 01:53
@knubie Thanks for your testing!
I merged `bugfix/shadow-cljs` branch to master, and released it.
https://github.com/liquidz/vim-iced/pull/129

**Closed by liquidz** 2019-06-19 01:53 UTC
Labels: bug
